### ISSUE TITLE
Hamburger Animation 

### ISSUE THREAD

**Issue by bmccoy11** [braginteractive/materialwp#1]
Shouldn't the navigation menu button use the Material Design hamburger animation? You can find CSS for it [here](http://codepen.io/swirlycheetah/pen/cFtzb).

**Comment by braginteractive** [comment]
Right now the theme is using https://github.com/FezVrasta/bootstrap-material-design to apply the material design to Bootstrap elements. That script is still using a Bootstrap style nav button.

**Comment by bmccoy11** [comment]
Thanks for the super quick reply! I'll report this over there now.
