### ISSUE TITLE
Mobile Menu Button Not Material Design

### ISSUE THREAD

**Issue by bmccoy11** [braginteractive/materialwp#10]
The menu button for mobile devices isn't flat, and has a weird looking gradient that doesn't match the rest of the page. When a dropdown menu is clicked on a mobile device, the button becomes un-pressed.

**Comment by braginteractive** [comment]
Fixed.

**Comment by bmccoy11** [comment]
Looks a lot better, but could use a hamburger animation.
http://codepen.io/swirlycheetah/pen/cFtzb
