### ISSUE TITLE
Poorly formatted zip available on site

### ISSUE THREAD

**Issue by bmos** [braginteractive/materialwp#13]
The zip on the site contains an identically-named subfolder which prevents Wordpress from displaying the preview image (unless I unzip it and rezip the contents without the extra directory level).

Hopefully I'm being clear.

**Comment by braginteractive** [comment]
I don't think I can change the zip to just materialwp. I think it has to be %repository-name%-name. So even if I changed the name you would still have to unzip it.

**Comment by bmos** [comment]
The name of the zip isn't the issue, it's the extra top level of the folder hierarchy.
It's a zipped folder rather than a zipped collection of files and folders.

This is the zip you provide:
![capture](https://cloud.githubusercontent.com/assets/1916835/6340484/9bdcc254-bb8d-11e4-8e39-fd738ac3114b.PNG)

This is the zip I have to convert it to if I want the theme image to appear in Wordpress:
![capture2](https://cloud.githubusercontent.com/assets/1916835/6340455/5e0902c6-bb8d-11e4-8ae5-8643b67edf1b.PNG)

After changing the zip Wordpress shows the Theme as this:
![capture](https://cloud.githubusercontent.com/assets/1916835/6340516/f3c496a4-bb8d-11e4-8768-91185fd09e70.PNG)

**Comment by braginteractive** [comment]
Yeah, I dont have control over this.

**Comment by bmos** [comment]
Wow, can't believe it's been 5 years already.
Here's how to fix:
1. Open the folder you have been zipping up
2. Select all inside the folder
3. Right click and compress (on mac) or send to zip (on PC)

This will give you a zip file without the extra top level directory.

If you right-click the folder and compress/send to zip, it leaves the extra directory which adds many additional steps for prospective users. If you select the contents and compress/send to zip, it works as intended.
