### ISSUE TITLE
how to make the header sticky ?

### ISSUE THREAD

**Issue by pmigneault** [braginteractive/materialwp#15]
What should I do to give a sticky attribute to the header, so the header will be visible at all times?

**Comment by braginteractive** [comment]
Bootstrap has a .navbar-fixed-top class that you can add to the navbar in the header.php file. 

http://getbootstrap.com/components/#navbar-fixed-top

**Comment by pmigneault** [comment]
It works great. 

It's possible to put a transparency in the same way?

**Comment by braginteractive** [comment]
You will need to add custom CSS for further changes.

**Comment by pmigneault** [comment]
thanks a lot
