### ISSUE TITLE
Portfolio/Unyson Issues

### ISSUE THREAD

**Issue by davidbwaters** [braginteractive/materialwp#16]
Hi, 

With the latest version of Unyson, the portfolio is broken.  As soon as I activate the Portfolio feature in Unyson the site gets an error similar to the one described here: https://github.com/ThemeFuse/Unyson/issues/378

I tried replacing the code as they did and the error disappears, but the portfolio doesn't work at all.  

Thanks

**Comment by braginteractive** [comment]
The more I use Unyson, the more I don't really like it. I am probably going to remove it in the near future.

**Comment by braginteractive** [comment]
Unyson has been removed
