### ISSUE TITLE
Wrong license

### ISSUE THREAD

**Issue by FezVrasta** [braginteractive/materialwp#2]
Hello you are using my framework and you are attributing to you the rights of the license.

Any derived work from my project must include the license of my project and any person willing to use any derived work in commercial projects must ask my permission, not yours.

Please correct your license asap.

**Comment by braginteractive** [comment]
My bad. I updated the license to include yours at the top. Does that work for you?

**Comment by FezVrasta** [comment]
Please contact me trough my website (mywebexpression.com) to discuss about

> This software may be sold if used inside a software which uses it as dependency, in any case, this license must be included in the software. This always after have fulfilled author's conditions.

**Comment by braginteractive** [comment]
Email sent via contact form.
