### ISSUE TITLE
Title appears more than once only when theme is enabled.

### ISSUE THREAD

**Issue by iosefmann** [braginteractive/materialwp#23]
![image](https://cloud.githubusercontent.com/assets/14027493/9561167/a0b7004a-4e7d-11e5-9ca2-4a2836c04b44.png)
Title tag with another theme

![screen shot 2015-08-29 at 6 40 26 pm](https://cloud.githubusercontent.com/assets/14027493/9561185/aa81b6a0-4e7e-11e5-99f4-5a247f29310f.png)
Title tag with theme

**Comment by braginteractive** [comment]
This should now be fixed if you pull down the latest header.php file.
