### ISSUE TITLE
page title is double

### ISSUE THREAD

**Issue by UncleDan** [braginteractive/materialwp#24]
Using materialwp on my new site http://www.danielelolli.it/
I see the blog title and subtitle twice in the page title (on the browser tab).
My problem or a little bug? Any fix?

**Comment by HoshinoTouko** [comment]
I have the same problem. I install SEO Ultimate and the problem solved

**Comment by braginteractive** [comment]
This should be fixed if you pull the latest files down.

**Comment by UncleDan** [comment]
I just re-installed the theme with files freshly downloaded from the Github repo (rel. 0.0.4, commit b50d345a78) but the bug seems still there.

![image](https://cloud.githubusercontent.com/assets/741453/9854938/aecb6e2e-5b0b-11e5-8564-eec74076d1f8.png)

**Comment by braginteractive** [comment]
Look in your header.php file and make sure you do not have a title tag listed. WordPress takes care of this now. 

Also, are you using any type of SEO plugin?

**Comment by UncleDan** [comment]
First: thank you for your patience.
![image](https://cloud.githubusercontent.com/assets/741453/9855434/771493ea-5b0e-11e5-9013-2447ee092c8e.png)
![image](https://cloud.githubusercontent.com/assets/741453/9855466/a749c094-5b0e-11e5-85ca-001a664fef17.png)

**Comment by braginteractive** [comment]
The title is probably cached then unless something is setting the title.

**Comment by UncleDan** [comment]
I think the problem is the dot in line 53 of file extras.php, but I do not know either if the function is used for something else or how to upload the correction ti Github.
![temp](https://cloud.githubusercontent.com/assets/741453/9873398/c8a627c8-5b9f-11e5-8ee7-4c4139e9a4e4.png)

**Comment by braginteractive** [comment]
Try the latest extras.php file now. It shouldn't be using that title section unless the user is using WP 4.1 or less

**Comment by UncleDan** [comment]
Perfect, thanks.
