### ISSUE TITLE
Require included PHP files using get_stylesheet_directory() instead of get_template_directory()

### ISSUE THREAD

**Issue by jankal** [braginteractive/materialwp#26]
I'm just now programming a child theme, and want to override the bootstrap-walker, to be compatible with a menu whith a depth more than 2. But it's not possible to override it, cause you required it with get_template_directory().

**Comment by braginteractive** [comment]
Yeah, that file really isnt meant to be overwritten.. If you are building a new menu it seems like you would remove the call to the custom walker class in the header.php file and replace it with the menu you build. 

Other options would be the following:
http://www.organizedthemes.com/advanced-child-theme-usage/
http://stackoverflow.com/questions/14597060/override-theme-options-php-file
