### ISSUE TITLE
Suggestion for input

### ISSUE THREAD

**Issue by onigetoc** [braginteractive/materialwp#27]
Suggestion, adding the all input effect like here: 
http://fezvrasta.github.io/bootstrap-material-design/#input

**Comment by braginteractive** [comment]
Which inputs are you talking about?

**Comment by onigetoc** [comment]
Form input and textarea, The Meterial design effects you can see in the url i provide you.

**Comment by braginteractive** [comment]
The front-end of WP themes don't really have inputs and textareas.. So that is why i am asking what you are referring too. Maybe the comment forms? Either way, the theme uses http://fezvrasta.github.io/bootstrap-material-design so you can add any class you style you need from the framework.

**Comment by onigetoc** [comment]
In the comments sections and in contact form :)
