### ISSUE TITLE
Word breaking not working correctly (Firefox)

### ISSUE THREAD

**Issue by hous3m4ster** [braginteractive/materialwp#28]
Hello,

When I type a large piece of text and display it in the MaterialWP theme lots of text doesn't format correctly. At the end of a line half of a word gets put at the end of the line and the second half gets put on the next line as the beginning word. (on firefox)

[http://vtvpioniers.nl](http://vtvpioniers.nl) 

Regards,

**Comment by braginteractive** [comment]
What page are you seeing this on? Is it a title or paragraph text?

**Comment by hous3m4ster** [comment]
every page on http://vtvpioniers.nl/
(example: [http://vtvpioniers.nl/?page_id=8](http://vtvpioniers.nl/?page_id=8))
both title and paragraph text

**Comment by braginteractive** [comment]
Looks fine to me in Firefox?

Have you tried targeting whatever you are having problems with CSS? http://www.w3schools.com/cssref/css3_pr_word-wrap.asp
