### ISSUE TITLE
Is it possible to specify individual layout for each page or post

### ISSUE THREAD

**Issue by johnsonz** [braginteractive/materialwp#30]
Is it possible to specify individual layout for each page or post? Such as some posts use the layout without   sidebar, or some use the layout with left sidebar or right sidebar.

**Comment by braginteractive** [comment]
Sure, you would have to create custom WP page templates though. (https://developer.wordpress.org/themes/template-files-section/page-template-files/page-templates/) 

In these page templates you can use the WP loop to display the posts or page content you would like.
