### ISSUE TITLE
How to change the NavBar?

### ISSUE THREAD

**Issue by RZR666** [braginteractive/materialwp#33]
Hi, 

Love the theme.

But how do you use a Navbar like on http://materialwp.com/ with the dropdown menu and search?

Thanks

**Comment by KeesWD** [comment]
Hi,

Isn't it possible to answer this question?
Is support stopped on this theme?

If so, please let us know, so we can decide if this theme is still meeting our needs.

Cheers,
KeesWD

**Comment by braginteractive** [comment]
@RZR666 did you create and set a primary menu in the WP dashboard? You will have to create a child theme or edit the header.php file and add a call to [the get_search_form() ](https://developer.wordpress.org/reference/functions/get_search_form/) if you want the search form in the header.

@KeesWD support may not be instant for this free theme.
