### ISSUE TITLE
How do you put an image on the left of the cards?

### ISSUE THREAD

**Issue by KrunchMuffin** [braginteractive/materialwp#36]
I have been trying w/o luck.

**Comment by braginteractive** [comment]
You will need to edit the content.php template and edit the markup to display the featured image to the left.

**Comment by KrunchMuffin** [comment]
I know that, but the markup to make it work with the card code

**Comment by braginteractive** [comment]
The markup would have to be custom. I dont see any card markup with the image on the left here: http://fezvrasta.github.io/bootstrap-material-design/
