### ISSUE TITLE
Material style not applied

### ISSUE THREAD

**Issue by Raxdiam** [braginteractive/materialwp#40]
I could be mistaken, but when I installed the theme on a fresh install of Wordpress, it does not look how it is supposed to.

Here is a screenshot of what the site currently looks like:
![MaterialWP installed on new site](https://i.imgur.com/gWHeLwo.png)

If this **is** in fact how it's supposed to look the first time it is installed, how do I make it look the way it does in the demo? If this is indeed **not** how it's supposed to look, then is this theme simply out of date, or did I do something wrong?

**Comment by dhaval47** [comment]
They provided different code in Download folder. 
I had this query and I checked markup of demo and theme they provided and both are different.

**Comment by dhaval47** [comment]
I thought they updated code and didn't updated **screenshot.png**
