### ISSUE TITLE
Overlay on hover not working

### ISSUE THREAD

**Issue by Amigo1000** [braginteractive/materialwp#42]
Hello,

I've added this code, but the hover overlay is not working unfortunately. How can this be resolved please?

   
    <div class="view overlay">
      <img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Others/images/15.jpg" alt="Card image cap">
      <a href="#">
      <div class="mask flex-center rgba-red-strong">
      </a>
    </div>

**Comment by Amigo1000** [comment]
Also I created a stylesheet, the correct wordpress method, but the parent stylesheet is not loading... ?

**Comment by braginteractive** [comment]
Where are you finding this overlay class?

**Comment by Amigo1000** [comment]
Hello, I am trying out the MDB Wordpress theme.

I made a child-theme, and somehow the master css did not work.
So now I've added some files and it's working better. Although animations not working yet...

**Comment by Amigo1000** [comment]
Hello, how can I make the widget contents center?

**Comment by braginteractive** [comment]
Sorry, the "Issues" section is for problems with the theme, not general customization questions. 

Please do some research on your end on how to use CSS to make changes to the theme.
