### ISSUE TITLE
How to change the theme color?

### ISSUE THREAD

**Issue by NingLee** [braginteractive/materialwp#6]
How see the bootstrap components and I know there are several color options, such as, default,primary,warning,error and so on. 

But I use the theme, I can't find a simple way to change the color to another.

Can you provide the GUI to support this or tell me which file to change to switch the color?

Thank you.

**Comment by braginteractive** [comment]
The easiest way would be to  target the elements with CSS to change the color. 

Another option would be to create a child theme and edit the classes that are setting the colors in the various files.  

I am close to releasing a premium version that is similar to this theme that will have options to change the colors.

**Comment by NingLee** [comment]
Can you tell me which css file to change to modify the color? 
including the panel, button components and so on.
Thank you.

**Comment by braginteractive** [comment]
I guess you didn't take the child theme route.. http://codex.wordpress.org/Child_Themes

It would be style.css
