### ISSUE TITLE
Placeholder Text In Search Bar

### ISSUE THREAD

**Issue by bmccoy11** [braginteractive/materialwp#7]
Instead of no placeholder text in the search bar, it should say something like "Search" instead of just a blank white bar.

**Comment by braginteractive** [comment]
Depending on what browser you are using it does have a  "Search" placeholder. Check out searchform.php

**Comment by bmccoy11** [comment]
On my website, https://bmccoy.cf , it doesn't display the placeholder text in Chrome 41, Firefox 34, or Internet Explorer 11. Also, when I click the search bar, it shrinks a tiny bit and re-expands when another object is clicked on,

**Comment by braginteractive** [comment]
I can't seem to figure out why the white background is happening since the latest version of https://github.com/FezVrasta/bootstrap-material-design 

I removed it for now and changed the header a bit.

**Comment by bmccoy11** [comment]
Alrighty then.

**Comment by braginteractive** [comment]
The sidebar search widget seems to work well.

**Comment by bmccoy11** [comment]
Hm. I just updated header.php, searchform.php, and functions.php to the new revisions, now all the navigation buttons are positioned on the right. I don't like that. :(

**Comment by braginteractive** [comment]
Change it. Look for navbar-right in the header.php file and replace it with navbar-left.

**Comment by braginteractive** [comment]
Fixed the search background color. Navbar now set back to the right again.

**Comment by bmccoy11** [comment]
Fixed!
